name: 🐞 Bug
description: Create a report to help us fix an issue with the system
title: "[BUG] <title>"
labels: [bug]
body:
  - type: dropdown
    id: support
    attributes:
      label: Have you contacted the support team about this?
      description: |
        Thanks for taking the time to create a bug report. If you are not quite sure what's going wrong, or why something is happening, please create a Support Ticket in the first instance by emailing [support@adam-rms.com](mailto:support@adam-rms.com).
        Our support team will troubleshoot with you and try to figure out why something is doing what it's doing! They may be able to fix it with you, or they may ask you to open an issue here
      options:
        - No - I'm self hosting AdamRMS so the support team can't help
        - No - I haven't yet heard back from Support, and following the posted security policy I am now publicly reporting the existence of an issue, to make direct contact with a maintainer
        - No - I have steps to reproduce this issue, and I think I know what's causing it
        - No - I'm an experienced maintainer and I've found/suspect I've found root cause
        - Yes - Support then came back to me and suggested I report it here
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of AdamRMS are you running?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: | 
        A concise description of what you're experiencing
        Please **do not** include any sensitive information from your business/ that you have access to, the contents of this form are posted publicly on the internet
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: |
        Steps to reproduce the behavior.
        Please **do not** include any sensitive information from your business/ that you have access to, the contents of this form are posted publicly on the internet
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: input
    attributes:
      label: How are you accessing AdamRMS?
      description: |
        Visit [whatsmybrowser.org](https://www.whatsmybrowser.org/) or [whatismybrowser.com](https://www.whatismybrowser.com/) and paste the link generated in the box below 
      placeholder: whatsmybrowser.org/b/QAV3Q
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
